#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { ensureDir, stateRoot, writeJson, appendReceipt, parseArgs } from './lib.mjs';

const archetypes = {
  software: ['architect','builder','security-reviewer','qa-reviewer'],
  web: ['product-architect','frontend-builder','backend-builder','qa-reviewer'],
  research: ['investigator','synthesist','fact-checker'],
  content: ['strategist','writer','editor','fact-checker'],
  game: ['game-architect','gameplay-builder','systems-builder','qa-reviewer'],
  operations: ['operator','automation-builder','risk-reviewer']
};

export function inferArchetype(root = process.cwd()) {
  if (fs.existsSync(path.join(root,'package.json'))) return 'software';
  if (fs.existsSync(path.join(root,'Cargo.toml')) || fs.existsSync(path.join(root,'pyproject.toml'))) return 'software';
  return 'software';
}

export function initTeam({ root = process.cwd(), archetype = 'auto', name = 'default', brief = '' }) {
  const selected = archetype === 'auto' ? inferArchetype(root) : archetype;
  const roles = archetypes[selected];
  if (!roles) throw new Error(`unknown archetype: ${selected}`);
  const base = path.join(stateRoot(root),'team');
  const agentDir = path.join(stateRoot(root),'agents');
  ensureDir(base); ensureDir(agentDir);
  const team = { schema:1, name, archetype:selected, brief, roles, generatedAt:new Date().toISOString() };
  writeJson(path.join(base,'team.json'),team);
  for (const role of roles) {
    const file = path.join(agentDir,`${role}.md`);
    fs.writeFileSync(file, `# ${role}\n\nProject role generated by AG Kit Team Assembly.\n\n## Mission\nWork only inside the role boundary for this project. Read the project brief, shared core, loaded skills, and relevant packs before acting.\n\n## Coordination\nReturn evidence, artifacts, assumptions, and handoff notes. Never claim another role's verification as your own.\n`);
  }
  appendReceipt(root,'team',{action:'init',name,archetype:selected,roles});
  return team;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = parseArgs(process.argv.slice(2));
  const cmd = args._[0];
  if (cmd !== 'init') { console.log('Usage: node engine/team.mjs init [--archetype software|web|research|content|game|operations] [--name name] [--brief text] [--path dir]'); process.exitCode=1; }
  else console.log(JSON.stringify(initTeam({root:args.path||process.cwd(),archetype:args.archetype||'auto',name:args.name||'default',brief:args.brief||''}),null,2));
}
