const lines = (values) => `${values.join("\n")}\n`;

export const mainHelp = () => lines([
  "AG Kit — lean multi-runtime operating layer for AI coding agents",
  "",
  "Usage: ag-kit <command> [options]",
  "",
  "`npm install -g @vudovn/ag-kit` installs the CLI only; project files change only after a runtime install or legacy `init`.",
  "",
  "Core workflow:",
  "  prompt-check <prompt...>      Check whether a task is concrete enough to act without guessing",
  "  route <task...>              Classify role, effort, and flow depth",
  "  flow <subcommand>            Start/status/approve gated project flows",
  "  team                         Generate project-specific specialists",
  "  cross-audit [target]         Run independent read-only reviewers",
  "  preflight                    Run blocking release/project gates",
  "",
  "Memory & continuity:",
  "  memory <subcommand>          Evolving local-first project memory",
  "  memory semantic <command>    Optional local vector status/rebuild/recall (model download opt-in)",
  "  brain <subcommand>           Opt-in cross-project memory registry/search",
  "  handoff <subcommand>         Create/show compact continuation artifacts",
  "  compress <file>              Compact a project context artifact",
  "",
  "Runtime & integration:",
  "  runtime detect               Detect supported runtimes already present",
  "  runtime install-present      Install adapters for detected runtimes",
  "  runtime list                 List supported runtime targets",
  "  runtime install <runtime>    Install one runtime adapter",
  "  runtime doctor [runtime]     Verify lifecycle/wiring state",
  "  runtime uninstall <runtime>  Remove only AG Kit-owned projection state",
  "  mcp serve                    Serve the project-local MCP bridge",
  "",
  "Efficiency & local state:",
  "  run <command> [args...]      Run with bounded output + full sandbox log",
  "  observe <kind>               Record explicit local observability metrics",
  "  dashboard <subcommand>       Inspect/start/stop the localhost dashboard",
  "  personalize <subcommand>     Evidence-backed preferences/privacy controls",
  "  design <subcommand>          Create/check the portable DESIGN.md contract",
  "",
  "Legacy managed-tree lifecycle:",
  "  init                         Safely install/merge the Antigravity .agents tree",
  "  update                       Merge-aware update with backup/conflict report",
  "  rollback                     Restore a pre-update .agents backup",
  "  status                       Show legacy managed-tree installation status",
  "",
  "Global options:",
  "  -h, --help                   Show this help",
  "  -v, --version                Show CLI version",
  "",
  "Run `ag-kit runtime --help` for runtime lifecycle commands or `<command> --help` for command-specific options.",
]);

export const runtimeHelp = () => lines([
  "AG Kit runtime lifecycle",
  "",
  "Usage: ag-kit runtime <command> [options]",
  "",
  "Commands:",
  "  detect                       Detect installed/configured runtime targets",
  "  install-present              Install adapters for every detected runtime",
  "  list                         List all supported runtime targets",
  "  install <runtime>            Install one runtime projection",
  "  doctor [runtime]             Report live/standing-by/degraded/untouched state",
  "  uninstall <runtime>          Safely remove AG Kit-owned projection state",
  "",
  "Examples:",
  "  ag-kit runtime detect",
  "  ag-kit runtime install-present",
  "  ag-kit runtime install antigravity",
  "  ag-kit runtime doctor",
  "",
  "Project-scoped config is preferred. Global-only integrations are staged for explicit activation.",
]);

export const printMainHelp = () => process.stdout.write(mainHelp());
export const printRuntimeHelp = () => process.stdout.write(runtimeHelp());
